<a href="https://colab.research.google.com/github/anandchauhan21/AI_ML_Notes/blob/main/Module2/Lesson4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧠 Concept Recap — Linear Algebra in ML

Linear Algebra is the **mathematical foundation** of Machine Learning.

---

## 🔹 Why Linear Algebra?
- Data is stored as **vectors & matrices**
- Model parameters are **matrices**
- Predictions involve **matrix multiplication**

---

## 🔹 Key Concepts
- Scalars
- Vectors
- Matrices
- Matrix operations
- Dot product

In [1]:
import numpy as np

# Scalar
a = 5

# Vector
v = np.array([1, 2, 3])

# Matrix
M = np.array([[1, 2], [3, 4]])

print("Scalar:", a)
print("Vector:", v)
print("Matrix:\n", M)


Scalar: 5
Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]]


In [2]:
v1 = np.array([2, 4])
v2 = np.array([1, 3])

print("Addition:", v1 + v2)
print("Subtraction:", v1 - v2)
print("Scalar Multiplication:", 3 * v1)


Addition: [3 7]
Subtraction: [1 1]
Scalar Multiplication: [ 6 12]


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A + B:\n", A + B)
print("A - B:\n", A - B)
print("A × B:\n", A @ B)

A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]
A × B:
 [[19 22]
 [43 50]]


In [4]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Dot Product:", np.dot(x, y))

Dot Product: 32


In [5]:
C = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", C)
print("Transpose:\n", C.T)

Matrix:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [6]:
# Simple linear model y = wx + b
w = np.array([2, 3])
x = np.array([1, 2])
b = 1

y = np.dot(w, x) + b
print("Model Output:", y)

Model Output: 9


In [ ]:
# Try changing vector values
x = np.array([3, 4])
w = np.array([1, 2])
b = 2

print("Prediction:", np.dot(w, x) + b)

# 🧩 Lesson Recap

You learned:
✅ Scalars, vectors, and matrices  
✅ Vector and matrix operations  
✅ Dot product and transpose  
✅ How linear algebra is used in ML models  

---

### 🔜 Next Lesson:
**Lesson 5: Calculus for Optimization**

## 💬 Viva Questions

1. Why is linear algebra important in ML?
2. What is a vector?
3. What does dot product represent?
4. What is a matrix transpose?
5. How is matrix multiplication used in ML?